title_name = "DEAD OR ALIVE 4"
title_id = "544307D1" # TC-2001
hash = "7F840B8DEFDB5C5E" # default.xex
#media_id = "2AD7FA3A"

[[patch]]
    name = "Restore Alpha-152 Character Slot"
    desc = "sets slot flag to 1 (from 0)"
    author = "ryu_highabusa"
    is_enabled = true

    [[patch.be8]]
        address = 0x821b52d3 
        value = 0x01
		
[[patch]]
    name = "Remove 30-hit Combo Limit"
    desc = ""
    author = "ryu_highabusa"
    is_enabled = true
	
	[[patch.be8]]
		address = 0x82502197
		value = 0xff
		
[[patch]]
	name = "Increase Max Character Distance"
	desc = "Increases the maximum distance between characters from 6.0 to 33.6475"
	author = "ryu_highabusa"
	is_enabled = true
	
	[[patch.be32]]
		address = 0x822a9df8
		value = 0x42069710


[[patch]]
    name = "Player_1 is ALPHA-152"
    desc = ""
    author = ""
    is_enabled = false

    [[patch.be8]]
        address = 0x8250e52b 
        value = 0x10
#    [[patch.be8]]
#        address = 0x830efb5e 
#       value = 0x00
#    [[patch.be8]]
#	    address = 0x830ef631 
#        value = 0x10
#    [[patch.be8]]
#        address = 0x830ef679 
#        value = 0x00


[[patch]]
    name = "alpha152 unlock test"
    desc = "sets character flag to 1 (from 0)"
    author = ""
    is_enabled = true

    [[patch.be8]]
        address = 0x831a0aee
        value = 0x01
[[patch]]
    name = "alpha152 unlock test default costume value"
    desc = "sets default costume value to 0x02 (from 0x22, which is a weird flag)"
    author = ""
    is_enabled = true

    [[patch.be8]]
        address = 0x82e2d455
        value = 0x02		
[[patch]]
    name = "change character select read value from 22 to 23? (from 0x16 to 0x17, from 0x17 to 0x18)"
    desc = ""
    author = ""
    is_enabled = false

    [[patch.be8]]
        address = 0x822f66e3
        value = 0x17		
	[[patch.be8]]
		address = 0x822f667b
		value = 0x18
[[patch]]
    name = "change value from 23 to 24? (from 0x17 to 0x18)"
    desc = ""
    author = ""
    is_enabled = false
	
	[[patch.be8]]
		address = 0x825123ab
		value = 0x18
	[[patch.be8]]
		address = 0x8251242f
		value = 0x18
	[[patch.be8]]
		address = 0x825124eb
		value = 0x18
[[patch]]
    name = "remove 0x14 flag"
    desc = ""
    author = ""
    is_enabled = false
	
	[[patch.be8]]
		address = 0x823f3593
		value = 0xff
[[patch]]
    name = "test2"
    desc = ""
    author = ""
    is_enabled = false
	
	[[patch.be8]]
		address = 0x82e2d457
		value = 0x02
				
[[patch]]
    name = "remove alpha152 lockout"
    desc = ""
    author = ""
    is_enabled = true
	
	[[patch.be8]]
		address = 0x82c54f3c
		value = 0xff
		
[[patch]]
    name = "add alpha152 to unlockables??"
    desc = ""
    author = ""
    is_enabled = true
	
	[[patch.be8]]
		address = 0x82c54f3a
		value = 0x10
	[[patch.be8]]
		address = 0x82c54f3b
		value = 0xff			

